server:
  port: 9000
eureke:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
spring:
  application:
    name: eureka-server