server:
  port: 9102
eureke:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:9102/eureka/
spring:
  application:
    name: eureka-server