#mariadb
spring:
  datasource:
    url: jdbc:mariadb://localhost:6666/message_infraction?createDatabaseIfNotExist=true
    username: root
    password: admin
    driver-clas-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    datasource-plateform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
#swagger2
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
#    profiles:
#      active: usage_message
#Eureka
eureke:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
